[package]
name = "a4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imageproc = "0.24.0"
image = "0.25.1"
walkdir = "2.5.0"
rect_packer = "0.2.1"
pdf = "0.9.0"